#!/bin/bash

DOWNLOADS_DIR="$HOME/Downloads"

# Organize based on extensions
for file in "$DOWNLOADS_DIR"/*; do
    if [ -f "$file" ]; then
        extension="${file##*.}"
        mkdir -p "$DOWNLOADS_DIR/$extension"
        mv "$file" "$DOWNLOADS_DIR/$extension/"
    fi
done

echo "Files organized successfully!"
